server:
  port: 9001
spring:
  application:
    name: microservice-user
  zipkin:
    base-url: http://127.0.0.1:9041
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 #頻率
  datasource:
    url: jdbc:mysql://172.20.10.7:3306/spring_cloud?characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true #自動建立table
    database: mysql
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:  #客戶端註冊地址
       defaultZone: http://127.0.0.1:8888/eureka
  instance:
    prefer-ip-address: true  #優先使用該服務的IP地址註冊到eureka
